artifact_location: file:D:/Labmentix/Aerial-Object-Detection-Bird-vs-Drone/runs/mlflow/523339808488282604
creation_time: 1764318102685
experiment_id: '523339808488282604'
last_update_time: 1764318102685
lifecycle_stage: active
name: /Shared/Ultralytics
