artifact_location: file:D:/Labmentix/Aerial-Object-Detection-Bird-vs-Drone/runs/mlflow/0
creation_time: 1764318102634
experiment_id: '0'
last_update_time: 1764318102634
lifecycle_stage: active
name: Default
